const FINANCE = [
  {
    productType: "deposit",
    productTitle: "예금",
    products: [
      {
        title: "우리 첫거래우대 정기예금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 8,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기예금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 5,
        totalAsset: 600000,
        monthlyPayment: 200000,
      },
    ],
  },
  {
    productType: "installment",
    productTitle: "적금",
    products: [
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 1,
        totalAsset: 1100000,
        monthlyPayment: 50000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 5,
        totalAsset: 900000,
        monthlyPayment: 300000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 11,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 7,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 9,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
      {
        title: "우리 첫거래우대 정기적금",
        bank: "우리은행",
        bankLogo: "/src/assets/bank06.svg",
        stamp: 6,
        totalAsset: 900000,
        monthlyPayment: 100000,
      },
    ],
  },
];

export default FINANCE;
